FROM amazonlinux:latest as base

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum update -y; yum clean all

RUN yum install -y \
  git \
  python2 \
  python2-scons \
  gcc \
  gcc-c++ \
  make \
  boost-devel

WORKDIR /build
COPY . ./

# Commit where el-build-local branched off
RUN git fetch origin 175bae1bcfa539c82745c6139e418b4c88158228 \
  && git reset --hard 175bae1bcfa539c82745c6139e418b4c88158228 \
  && SCONSFLAGS="-j 20" scons --disable-warnings-as-errors --cache="all" --cache-dir="/tmp/scons/cache"


FROM base as final

WORKDIR /build
COPY . ./

COPY --from=base /build/build/cached /build/build/cached
COPY --from=base /tmp/scons/cache /tmp/scons/cache

RUN git fetch origin el-build-local \
  && git reset --hard origin/el-build-local \
  && SCONSFLAGS="-j 20" scons --disable-warnings-as-errors --cache="all" --cache-dir="/tmp/scons/cache"
